Match the exact string
Fixes:

Checking branch 3.13
From https://github.com/python/cpython
 * [new branch]              3.13       -> 3.13

1 1 10000 https://github.com/python/cpython/pull/136930
  gh-136914: Fix support of cached functions and properties in DocTest's lineno
computation (GH-136930)
    Backport to 3.13 missing
2 1 10000 https://github.com/python/cpython/pull/136890
  Fix typos in Doc/extending/extending.rst and Doc/library/shelve.rst
(GH-136890)
    Backport to 3.13 missing
3 1 10000 https://github.com/python/cpython/pull/136709
  gh-136710: Fix bad indentation in `os.chdir` docstring (GH-136709)
    Backport to 3.13 missing
4 1 10000 https://github.com/python/cpython/pull/136519
  Omit `Python/perf_jit_trampoline.c` from the `**/*jit*` CODEOWNERS rule
(#136519)
fatal: command line, 'Omit `Python/perf_jit_trampoline.c` from the `**/*jit*` CODEOWNERS rule (#136519)': Invalid preceding regular expression
Traceback (most recent call last):
  File "/home/runner/work/dashboard/dashboard/github-tools/needs_backport.py", line 214, in <module>
    main()
    ~~~~^^
  File "/home/runner/work/dashboard/dashboard/github-tools/needs_backport.py", line 170, in main
    candidates = check_prs(
        api, args.repo_path, branch, args.start, args.number, args.sort
    )
  File "/home/runner/work/dashboard/dashboard/github-tools/needs_backport.py", line 109, in check_prs
    if is_commit_title_in_branch(repo_path, title, branch_to_check):
       ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/dashboard/dashboard/github-tools/needs_backport.py", line 60, in is_commit_title_in_branch
    output = subprocess.check_output(
             ~~~~~~~~~~~~~~~~~~~~~~~^
        ["git", "log", "--grep", title, branch], cwd=repo_path
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ).decode("utf-8")
    ^
  File "/opt/hostedtoolcache/Python/3.13.5/x64/lib/python3.13/subprocess.py", line 472, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
               **kwargs).stdout
               ^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.13.5/x64/lib/python3.13/subprocess.py", line 577, in run
    raise CalledProcessError(retcode, process.args,
                             output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['git', 'log', '--grep', 'Omit `Python/perf_jit_trampoline.c` from the `**/*jit*` CODEOWNERS rule (#136519)', '3.13']' returned non-zero exit status 128.